# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Class')),
            ],
        ),
        migrations.RemoveField(
            model_name='iteration',
            name='course',
        ),
        migrations.RemoveField(
            model_name='iteration',
            name='users',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='score',
            new_name='points_earned',
        ),
        migrations.RemoveField(
            model_name='result',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='points_possible',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='iteration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Class'),
        ),
        migrations.DeleteModel(
            name='Iteration',
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Course'),
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.Student'),
            preserve_default=False,
        ),
    ]
