# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20161006_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='iteration',
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(to='base.Student'),
        ),
    ]
