# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20161018_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='base.Student'),
        ),
    ]
