# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20161021_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
