# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20161010_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='iteration',
            new_name='classtime',
        ),
    ]
