# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_assessment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='date',
        ),
        migrations.AlterField(
            model_name='result',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
