# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_result_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='submit_multiple',
            field=models.BooleanField(default=True),
        ),
    ]
